### ISSUE TITLE
Class Execution Runs in Background with Rust Client

### ISSUE THREAD

**Issue by cr0wst** [renatoathaydes/jgrab#2] opened 2018-07-20 15:35 UTC
When running a class that depends on the Spark Framework (http://sparkjava.com/) jgrab will execute the code but will not remain attached to the process.

# Steps to Reproduce

Create `HelloWorld.java` with the following code:

```java
// #jgrab com.sparkjava:spark-core:latest.release

import static spark.Spark.*;

public class HelloWorld {
    public static void main(String... args) {
        port(3001);
        get("/hello", (req, res) -> "Hello World!");
    }
}
```

Run `jgrab HelloWorld.java`.

Navigate browser to http://localhost:3001/hello. You should see the string "Hello World!" In the terminal, however, the jgrab process is no longer attached to the now-running Java process:

```sh
crow at gauss in ~/Documents
$ jgrab HelloWorld.java
=== JGrab Client - Starting daemon ===
=== JGrab Client - Daemon started, pid=95004 ===
=== JGrab Client - Connected! ===
crow at gauss in ~/Documents
$
```

In order to kill the process I have to `kill 95004`. Is there any way to keep the terminal attached?

# Things I Have Tried

- Stopping the daemon using `jgrab -s`. In the terminal it has indicated that the daemon stopped, but the application is still running:

```sh
95004 ttys001    0:03.10 java -jar /Users/crow/.jgrab/jgrab.jar --daemon
```

- Running without using the rust client `java -jar ~/.jgrab/jgrab.jar HelloWorld.java` seems to keep the process attached to the terminal.

**Comment by renatoathaydes** [comment] 2018-07-20 20:14
This is a little bit tricky... the problem is that JGrab runs as a Java daemon in the background, waiting for the Rust or Java client to send it some code to compile and run... It calls the main function and returns to the client immediately when the main function returns... the problem with Spark is that it starts a background Thread which it uses to run the server, so the main function just returns as soon as the server's Thread is started. So, there's no way for JGrab to know there's a background Thread still running that your code started!

The solution would be to get a reference to the `Thread` object used by the Spark server, then `join()` it in the main function, but I am not sure how you can get that `Thread` object.

Anyway, I would not consider this a bug in JGrab as it is doing what it says it does: run your `Runnable` or `main(String...)`... and waits for that to return.

Detecting any background Threads you started and waiting for those to die would be nearly impossible from the JGrab runner.

So I am closing this issue.

**Closed as completed by renatoathaydes** 2018-07-20 20:14 UTC

**Comment by cr0wst** [comment] 2018-07-20 20:15
Fair enough! I've got no issues bypassing the daemon.

Thanks! :)

**Comment by renatoathaydes** [comment] 2018-07-20 20:39
> Stopping the daemon using jgrab -s. In the terminal it has indicated that the daemon stopped, but the application is still running

Oh, that should be fixable... we should be calling `System.exit()` when the daemon is stopped like that, to avoid this process hanging! Will do that for the next release.
